id: opecha:P009313
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4302
  title: དམ་པའི་ཆོས་དང་འབྲེལ་བའི་ལེ་ཚན་སུམ་ཅུ་རྩ་གཉིས་ཀྱི་གྲངས་ལྡན། ཐུབ་བསྟན་མཛེས་པའི་མཚན་བཟང་
  volume: ''
  author: ''
