id: P009313
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:32:51.207753
source_metadata:
  id: bdr:W1KG4302
  title: དམ་པའི་ཆོས་དང་འབྲེལ་བའི་ལེ་ཚན་སུམ་ཅུ་རྩ་གཉིས་ཀྱི་གྲངས་ལྡན། ཐུབ་བསྟན་མཛེས་པའི་མཚན་བཟང་
  author: ''
  volumes:
    1b8ae94463c44837a68733bbaefe051e:
      image_group_id: I1PD100511
      title: ''
      volume_number: 1
      total_pages: 140
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
