id: I3DF7DFE0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:55:32+00:00'
last_modified: '2022-06-08T10:07:49.294490+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4302
  title: དམ་པའི་ཆོས་དང་འབྲེལ་བའི་ལེ་ཚན་སུམ་ཅུ་རྩ་གཉིས་ཀྱི་གྲངས་ལྡན། ཐུབ་བསྟན་མཛེས་པའི་མཚན་བཟང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    C349:
      image_group_id: I1PD100511
      title: ''
      total_pages: 140
      order: 1
      base_file: C349.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
